### ISSUE TITLE
Add support for Rails::API

### ISSUE THREAD

**Issue by elhoyos** [Apipie/apipie-rails#22]
restapi is a nice feature you would like to have when building with [Rails::API](https://github.com/spastorino/rails-api).

On my attempts I've crossed with a couple of stoppers:
### ActiveController::Base references

On `lib/restapi/application.rb` the resource name will not be resolved correctly.

The error shown is `undefined method 'humanize' for nil:NilClass` on `resource_description.rb:23: 'initialize'`.

A possible lazy solution for it would be like this:

``` ruby
    def get_resource_name(klass)
      if klass.class == String
        klass
      elsif klass.class == Class && 
        (
          ActionController::Base.descendants.include?(klass) ||
          ActionController::API.descendants.include?(klass)
        )
        klass.controller_name
      end
    end
```

The previous override had to be done inside the gem. Apparently running the `restapi:static` task can't handle a monkey patch as suggested [here](http://stackoverflow.com/a/580504/638425).
### heredoc like expressions

I'm working with `Rails 3.2.6`, `Ruby 1.9.3` and the released gem version of `restapi`.

The provided examples that include a `DOC` expressions are not correctly processed. The error that is shown when running the `restapi:static` task is `wrong number of arguments (1 for 0)` on `restapi_module.rb, line 47`.

Example used:

```
config.app_info < <-DOC
    This is where you can inform user about your application and API
    in general.
 DOC
```

---

**Update 06/27**:
- Tested with bleeding edge restapi and problems are still the same
- Added specific message error for `ActiveController::Base references`
