### ISSUE TITLE
[v1.0] NoMethodError: undefined method `resource_id' for Apipie:Module

### ISSUE THREAD

**Issue by fiedl** [Apipie/apipie-rails#880]
After upgrading from v0.9.4 to v1.0.0, I'm getting a `NoMethodError`:

```
NoMethodError:
 undefined method `resource_id' for Apipie:Module
# /usr/local/bundle/gems/apipie-rails-1.0.0/lib/apipie/apipie_module.rb:34:in `method_missing'
# /usr/local/bundle/gems/apipie-rails-1.0.0/lib/apipie/extractor/collector.rb:22:in `ignore_call?'
# /usr/local/bundle/gems/apipie-rails-1.0.0/lib/apipie/extractor/collector.rb:28:in `handle_record'
# /usr/local/bundle/gems/apipie-rails-1.0.0/lib/apipie/extractor.rb:65:in `call_finished'
# /usr/local/bundle/gems/apipie-rails-1.0.0/lib/apipie/extractor/recorder.rb:157:in `process'
# /usr/local/bundle/gems/apipie-rails-1.0.0/lib/apipie/rspec/response_validation_helper.rb:165:in `process'
```

Has anyone seen this? Thanks!

**Comment by PanosCodes** [comment]
Have you tried the latest master ?

**Comment by fiedl** [comment]
Thanks, indeed it does work on the current `master` (528fb8ce163838592ed29e97142770835e6686e4).
