### PR TITLE
fix undefined method `content_tag`

### PR DESCRIPTION
**Pull request by emma-borhanian**
Started getting the following exception after bumping from 0.3.3 to 0.3.4:

```
ActionView::Template::Error:
 undefined method `content_tag' for #<Apipie::ApipiesController:0x007ffdb1a5e608>
# /Users/emma/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/apipie-rails-0.3.4/app/helpers/apipie_helper.rb:4:in `heading'
# /Users/emma/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/actionpack-4.2.1/lib/abstract_controller/helpers.rb:67:in `heading'
# /Users/emma/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/apipie-rails-0.3.4/app/views/apipie/apipies/_method_detail.erb:27:in `___sers_emma__rbenv_versions_______lib_ruby_gems_______gems_apipie_rails_______app_views_apipie_apipies__method_detail_erb__4191062763070027136_70363792007840'
# /Users/emma/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/actionview-4.2.1/lib/action_view/template.rb:145:in `block in render'
```

### CODE REVIEW

**Comment by IlyaBylich** [comment]
:+1: for this fix, I have same issue on rails 3.2.11

**Comment by saneshark** [comment]
I think this issue probably started manifesting itself for you guys after my PR #348 which addressed #251 was merged. The helper method was not being properly included as part of `ActionController::Base` but now I'm wondering how it is that that this worked for RailsApi prior to my patch?

It might also be worth testing that an existing helper having the same name `heading` within a projects ApplicationHelper doesn't override this method and have unintended consequences. To my knowledge these would all be in the same helper method namespace. Ideally the method would just be available in the context of this specific controller as a method and not pollute the global helper namespace.

**Comment by lumir** [comment]
I have the same issue, I can't use any of my def_param_group in my controller

**Comment by iNecas** [comment]
Thanks

**Comment by adityashankert** [comment]
hey we are trying to use the gem and someone have deleted the branch could someone do this pull to master or should i raise a pull request?
